name: Generate Release Hashes

on:
  release:
    types: [published]
    
permissions:
  contents: write
  packages: write

jobs:
  generate_hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Get release asset download URL
        id: get-url
        run: |
          # Use GitHub CLI to get the asset download URL
          ASSET_URL=$(gh release view --json assets -q '.assets[0].url')
          echo "Asset URL: $ASSET_URL"
          echo "::set-output name=asset_url::$ASSET_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release asset
        run: |
          # Use the asset download URL from the previous step
          curl -L -o ./asset.apk -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ steps.get-url.outputs.asset_url }}
      
      - name: Calculate SHA-256 Hashe
        run: |
          sha256sum > hashe.txt

      - name: Upload Hashe as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./hashe.txt
          asset_name: hashe.txt
          asset_content_type: text/plain
