name: Generate Release Hashes

on:
  release:
    types: [created]

jobs:
  generate_hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download release assets
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "Maple-Network/Waitify-Lock"
          version: "latest"
          file: "*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Calculate SHA-256 Hashes
        run: |
          for file in *.apk; do
            echo "$file" SHA-256 Hash:
            sha256sum "$file"
          done > hashes.txt

      - name: Upload Hashes as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./hashes.txt
          asset_name: hashes.txt
          asset_content_type: text/plain
